### ISSUE TITLE
paket remove nuget does also a general unwanted update

### ISSUE THREAD

**Issue by Vilmir** [fsprojects/Paket#1652]
### Description

Given a repository with no Groups 
and with several nuget package references
with some of them being outdated

When a paket remove nuget XXX is done to delete definitely a reference, paket also does a full update on every other package

Then everything is messed up

### Repro steps

1. On a repository that has several outdated nuget references

2. Call paket remove nuget XXX

### Expected behavior
The package XXX is removed from paket.dependencies and paket.lock

### Actual behavior
The package XXX is removed from paket.dependencies and paket.lock
And outdated packages are updated to latest version

### Known workarounds

Is deleting the given package lines in paket.dependencies and lock good enough? I don't think so.

### Related information 

* Win 7
* master
* .NET 4.6
* paket.exe 2.63.2.0

**Comment by forki** [comment]
can you please create a zip with a repro?

**Comment by Vilmir** [comment]
Could not repro without our Artifactory instance and private packages with 2.63.2.0

**Comment by forki** [comment]
paket runs install after remove and tries to keep versions as stable as possible.
Are you using prereleases or unlisted versions?

**Comment by Vilmir** [comment]
We do use prereleases:
`nuget CommandLineParser prerelease`

I have tried to repro with nuget.org and this prerelease, but it still does not repro on a dummy repo.

What do you mean by unlisted versions?

**Comment by forki** [comment]
it's possible to "delete" versions by unlisting them. If a version is unlisted then paket will try to use a different version during install.

**Comment by Vilmir** [comment]
Thanks for the explanation, as far as I know we never delete package versions in our private server

**Comment by forki** [comment]
the question is why install changes the dependencies for you, but without a repro it's really hard to say.

**Comment by Vilmir** [comment]
I can only repro this with our big codebase and its 70 custom packages, including 2 prereleases, using exclusively Artifactory v2.7 as source.
I think we can close this as not repro.

**Comment by cdrnet** [comment]
I had another case of this today where removing a prerelease paket did cause a full update in v2; but it worked fine in v3 without causing a full update. It looks like this issue has been fixed in v3, maybe as side effect of other changes in this area.

**Comment by forki** [comment]
Yeah we worked a bit in this and I hope it's fine when we finally go to v3

**Comment by scoobadog** [comment]
This issue still reproducible with latest Paket (3.19.8.0) and [scoobadog/Paket-1652](https://github.com/scoobadog/Paket-1652) repository.

**Comment by jamescrowley** [comment]
Seeing this here too.

**Comment by forki** [comment]
thanks for repoting a repro sample
