### ISSUE TITLE
Visual Studio 2017 .NET Core Auto Restore Doesn't Work

### ISSUE THREAD

**Issue by cjbhaines** [fsprojects/Paket#2087]
### Description

This is probably related to #2086.

Paket version: 4.0.0-alpha034

One of the great features about paket auto-restore is that you can take a fresh checkout of a repository, open Visual Studio and hit build and off you go. This seamless integration is what makes Paket so appealing. With the new .NET Core integration, you must run "dotnet restore" in order for the packages to be restored, even though Paket is managing the dependencies.

Would it be possible for Paket.Restore.targets to invoke "dotnet restore" automatically? I'm going to have a hard time convincing people to use Paket with .NET Core if everything they want to build they might have to be popping up a command prompt to call dotnet restore. 

If it's possible to do this, one thing to consider will be what happens if you many projects in the solution referencing the targets. Can restore just be called once? If not, will it have contention issues?

### Repro Steps

Please provide the steps required to reproduce the problem

1) Download https://dl.dropboxusercontent.com/u/49591225/Code/PaketTest_BuildDotnetCore.zip
2) Unzip solution
3) Open Visual Studio and build

### Expected Behavior

Packages are restored and build succeeds. 

### Actual Behaviour

Build fails due to missing packages.

/cc @davidKean @enricosada @theimowski

**Comment by isaacabraham** [comment]
Actually getting dotnet restore working with Paket is very important so that it fits within the new toolchain and standard commands. The idea is that dotnet restore will call out to msbuild which will in turn call paket.

I was under the impression that VS would call dotnet restore as part of the standard build process, but perhaps I'm wrong here.

**Comment by cjbhaines** [comment]
I wonder if Visual Studio is doing something intelligent where it looks at the csproj/project.json for changes and only calls dotnet restore if it sees a change?

**Comment by isaacabraham** [comment]
Hmmm but that assumes then that all nuget reference in the new world *must* be via the new <package> node I guess?

**Comment by enricosada** [comment]
@isaacabraham now the `dotnet restore` = `dotnet msbuild /t:Restore`. is exactly nuget restore.

As a note, that's not just related to .NET Core, that's the new msbuild project who can build also .NET Framework (and i hope that's the new standard for project from now on).

@cjbhaines can you pls increase msbuild output verbosity, and redo the repro? so we can see what is called, and why doesnt work.

**Comment by enricosada** [comment]
> Hmmm but that assumes then that all nuget reference in the new world must be via the new node I guess?

@isaacabraham no, `Reference` continue to work in new msbuild.

**Comment by cjbhaines** [comment]
@enricosada how do I do that inside VS? I'm not manually invoking MSBuild, I'm using the Visual Studio Build menu so I can't directly manipulate command line variables

**Comment by enricosada** [comment]
Tool -> options, there is msbuild verbosity somewhere.
Check google, is the same for old msbuild verbosity

**Comment by cjbhaines** [comment]
Got it, thanks.

https://dl.dropboxusercontent.com/u/49591225/Code/BuildLog.txt

**Comment by cjbhaines** [comment]
This is fixed in latest version

**Comment by janhebnes** [comment]
@cjbhaines could you define latest version more specifically ?
I have a fresh vs2017 install labelled 15.0.0+26228.9 where its seems to issue is still unsolved.

**Comment by cjbhaines** [comment]
there is still an issue noted in #2086 where you need to run a restore manually first before everything kicks in and starts working. Auto-restore isn't an explicit option with the new MSBuild format, it's all hooked in using build tasks to intercept the NuGet auto restore process so it's just on all the time without an additional Paket flag and build target.

**Comment by janhebnes** [comment]
I just noticed 15.0.0+26228.10 was out, and the issue seems to be solved for me in this version. 
Thanks for the quick reply.
