### ISSUE TITLE
paket restore not working with nexus nuget proxy and normalized version number

### ISSUE THREAD

**Issue by PMudra** [fsprojects/Paket#2320]
### Description

When I am trying to restore nuget package *SourceLink.Fake* with version 1.1.0 from a nexus nuget proxy server I get the following error message:

```
Paket version 4.8.5
Downloading SourceLink.Fake 1.1
Something went wrong while downloading SourceLink.Fake 1.1
Message: Could not download SourceLink.Fake 1.1.
    Couldn't get package details for package SourceLink.Fake 1.1 on http://localhost:8081/repository/nuget.org-proxy.
  ==> Trying again
Downloading SourceLink.Fake 1.1
Something went wrong while downloading SourceLink.Fake 1.1
Message: Could not download SourceLink.Fake 1.1.
    Couldn't get package details for package SourceLink.Fake 1.1 on http://localhost:8081/repository/nuget.org-proxy.
  ==> Last trial
Downloading SourceLink.Fake 1.1
Paket failed with:
        Could not download SourceLink.Fake 1.1.
    Couldn't get package details for package SourceLink.Fake 1.1 on http://localhost:8081/repository/nuget.org-proxy.
```

*SourceLink.Fake* is just an example. It will not work for any other package and version with trailing 0.

**paket.dependencies**
```
source http://localhost:8081/repository/nuget.org-proxy/
nuget SourceLink.Fake = 1.1.0
```

**paket.lock**
```
NUGET
  remote: http://localhost:8081/repository/nuget.org-proxy
    SourceLink.Fake (1.1)
```

#1777 might be related.

### Repro steps

1. Install nexus nuget proxy server. Easiest way using docker: `docker run -d -p 8081:8081 --name nexus sonatype/nexus3`. https://hub.docker.com/r/sonatype/nexus3/
2. Setup minimal project with paket.exe and paket.dependencies as stated above.
3. Run `.paket/paket.exe install`
4. Delete *package/* directory
5. Run `.paket/paket.exe clear-cache`
6. Run `.paket/paket.exe restore`

See [test.zip](https://github.com/fsprojects/Paket/files/983449/test.zip). Steps 3 and 4 can be skipped when using project in zip file.

### Expected behavior

The expected result is that paket restores the needed nuget paket to *package/* folder

### Actual behavior

An error occurs and the package is not restored.

I believe this is the important part of verbose output of `.paket/paket.exe restore` (full log: [verbose.txt](https://github.com/fsprojects/Paket/files/983470/verbose.txt)):

```
Downloading SourceLink.Fake 1.1
Response from http://localhost:8081/repository/nuget.org-proxy/Packages?$filter=(tolower(Id) eq 'sourcelink.fake') and (NormalizedVersion eq '1.1.0'):

<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<feed xml:base="http://localhost:8081/repository/nuget.org-proxy/" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom">
  <title type="text">Packages</title>
  <id>http://localhost:8081/repository/nuget.org-proxy/Packages</id>
  <updated>2017-05-08T12:37:06.654Z</updated>
  <link rel="self" title="Packages" href="Packages"/>
  <m:count>0</m:count>
</feed>
Response from http://localhost:8081/repository/nuget.org-proxy/Packages?$filter=(tolower(Id) eq 'sourcelink.fake') and (Version eq '1.1'):

<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<feed xml:base="http://localhost:8081/repository/nuget.org-proxy/" xmlns:d="http://schemas.microsoft.com/ado/2007/08/dataservices" xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" xmlns="http://www.w3.org/2005/Atom">
  <title type="text">Packages</title>
  <id>http://localhost:8081/repository/nuget.org-proxy/Packages</id>
  <updated>2017-05-08T12:37:06.890Z</updated>
  <link rel="self" title="Packages" href="Packages"/>
  <m:count>0</m:count>
</feed>
Error while retrieving 'http://localhost:8081/repository/nuget.org-proxy/Packages(Id='SourceLink.Fake',Version='1.1')': System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)<---
```

I believe the second request should be requesting `Version eq '1.1.0'` because `1.1.0` is the non-normalized version of the nuget package.

### Known workarounds

There are multiple ways to work around this issue:

1. Do not use nuget proxy but the official nuget.org server
2. Run `.paket/paket.exe update`
3. Delete *paket.lock* and run `.paket/paket.exe install`

**Comment by matthid** [comment]
Is this a regression? Ie is an older version of paket working?

**Comment by PMudra** [comment]
No, it does not seem so. I just tried it with versions 3.0.0 and 4.0.0 with the same result. Are there any specific versions I should try?

**Comment by b0urb4k1** [comment]
I am experiencing problems with Nexus 3 also.

> Paket version 5.1.7
> Resolving packages for group Build:
> - NuGet.CommandLine is pinned to 3.4.3
>    Package not available.
>      Message: Unable to retrieve package details for 'NuGet.CommandLine'-3.4.3

I downgraded to 4.8.7 which works with no problems.
So in my case this is for sure a regression.

Is there any way to use the bootstrapper to grab a specific version of Paket?

**Comment by forki** [comment]
yes you call with the version as argument https://fsprojects.github.io/Paket/bootstrapper.html

**Comment by b0urb4k1** [comment]
Thanks. It works now with the old version.
Here are some more errors i get. I am not sure if it helps or if i should run it in verbose mode maybe for a single package.

> - FluentAssertions is pinned to 4.13.0
> At least one 'next' link (index 0) returned a empty result (noticed on >'http://10.20.0.104:9001/repository/nuget-package-group/Packages()?>$filter=tolower%28Id%29+eq+%27commandlineparser%27&semVerLevel=2.0.0&$skip=40'): >>>['http://10.20.0.104:9001/repository/nuget-package-group/Packages()?>$skip=80&$filter=tolower%28Id%29+eq+%27commandlineparser%27&semVerLevel=2.0.0']
> - NUnit is pinned to 3.4.1
>Got multiple results in OData query ('http://10.20.0.104:9001/repository/nuget-package->group/Packages?$filter=(tolower(Id) eq 'nunit') and (Version eq '3.4.1')') for package NUnit 3.4.1, the >feed might be broken

**Comment by matthid** [comment]
@b0urb4k1 a full (with -v) and a minimal log (without -v) would be helpful. (+ dependencies file if possible)

**Comment by matthid** [comment]
Also if possible please add the same logs for the old (working) version. Thanks!

**Comment by b0urb4k1** [comment]
I compiled a gist with all the (hopefully) relevant data.
https://gist.github.com/b0urb4k1/c724bac98629e561d96040cdc106d59b

**Comment by matthid** [comment]
@b0urb4k1 Can you please open a new issue as I don't think it the same as the initial post.
Can you try setting `PAKET_RESOLVER_TASK_TIMEOUT` on higher values like 60000 for 60 seconds and report back?

**Comment by matthid** [comment]
@PMudra can you try again? This might have been solved recently.

**Comment by PMudra** [comment]
Unfortunately, I still get the same error message.

Version: 5.5.3

**Comment by forki** [comment]
ok I can repro!

**Comment by forki** [comment]
I just released paket 5.6.3 with a fix. But I assume it's a bug in sonatype since NormalizedVersion is 1.1.0 and it can't retrieve that. please also report it with sonatype directly.

**Comment by PMudra** [comment]
Thanks for the fix. I tried again and it is working now!

I found this issue on sonatypes jira: https://issues.sonatype.org/browse/NEXUS-6159
The missing NormalizedVersion is mentioned there.
