### ISSUE TITLE
Master branch fails to build

### ISSUE THREAD

**Issue by theimowski** [fsprojects/Paket#2345]
### Description

I'm unable to build current master tagged `5.0.0-beta003`.
```
λ build
Paket version 5.0.0-beta003
1 second - ready.
Building project with version: LocalBuild
Shortened DependencyGraph for Target All:
<== All
   <== GenerateDocs
      <== GenerateReferenceDocs
         <== RunTests
            <== Build
               <== Clean
               <== MSBuildRestore
                  <== AssemblyInfo
            <== BuildCore
               <== DotnetPackage
                  <== DotnetBuild
                     <== DotnetRestore
                        <== InstallDotNetCore
         <== GenerateHelp
            <== CleanDocs

The running order is:
  - Clean
  - AssemblyInfo
  - MSBuildRestore
  - Build
  - InstallDotNetCore
  - DotnetRestore
  - DotnetBuild
  - DotnetPackage
  - BuildCore
  - RunTests
  - CleanDocs
  - GenerateHelp
  - GenerateReferenceDocs
  - GenerateDocs
  - All
Running build with 1 worker
Starting Target: Clean 
Deleting contents of C:\github\Paket\src\Paket\obj
Deleting contents of C:\github\Paket\src\Paket.Bootstrapper\obj
Deleting contents of C:\github\Paket\src\Paket.Core\obj
Deleting contents of C:\github\Paket\tests\Paket.Bootstrapper.Tests\obj
Deleting contents of C:\github\Paket\tests\Paket.Tests\obj
Deleting contents of C:\github\Paket\tests\Paket.Bootstrapper.Tests\bin
Deleting contents of C:\github\Paket\tests\Paket.Tests\bin
Deleting contents of C:\github\Paket\bin
Finished Target: Clean
Starting Target: AssemblyInfo (==> Clean)
Created AssemblyInfo file "src\Paket\AssemblyInfo.fs".
Created AssemblyInfo file "src\Paket.Core\AssemblyInfo.fs".
Created AssemblyInfo file "C:\github\Paket\src\Paket.Bootstrapper\Properties\AssemblyInfo.cs".
Finished Target: AssemblyInfo
Starting Target: MSBuildRestore (==> AssemblyInfo)
Building project: C:\github\Paket\Paket.sln
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe  C:\github\Paket\Paket.sln /t:Restore /m      /p:RestorePackages="True" /logger:Fake.MsBuildLogger+ErrorLogger,"C:\github\Paket\packages\build\FAKE\tools\FakeLib.dll"
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 5/17/2017 8:35:41 PM.
     1>Project "C:\github\Paket\Paket.sln" on node 1 (Restore target(s)).
     1>ValidateSolutionConfiguration:
         Building solution configuration "Debug|Any CPU".
     1>Project "C:\github\Paket\Paket.sln" (1) is building "C:\github\Paket\tests\Paket.Tests\Paket.Tests.fsproj" (2) on node 1 (Restore target(s)).
     2>C:\github\Paket\tests\Paket.Tests\Paket.Tests.fsproj : error MSB4057: The target "Restore" does not exist in the project.
     2>Done Building Project "C:\github\Paket\tests\Paket.Tests\Paket.Tests.fsproj" (Restore target(s)) -- FAILED.
     1>Project "C:\github\Paket\Paket.sln" (1) is building "C:\github\Paket\src\Paket.Core\Paket.Core.fsproj" (3) on node 4 (Restore target(s)).
     3>C:\github\Paket\src\Paket.Core\Paket.Core.fsproj : error MSB4057: The target "Restore" does not exist in the project.
     3>Done Building Project "C:\github\Paket\src\Paket.Core\Paket.Core.fsproj" (Restore target(s)) -- FAILED.
     1>Project "C:\github\Paket\Paket.sln" (1) is building "C:\github\Paket\src\Paket\Paket.fsproj" (4) on node 2 (Restore target(s)).
     4>C:\github\Paket\src\Paket\Paket.fsproj : error MSB4057: The target "Restore" does not exist in the project.
     4>Done Building Project "C:\github\Paket\src\Paket\Paket.fsproj" (Restore target(s)) -- FAILED.
     1>Project "C:\github\Paket\Paket.sln" (1) is building "C:\github\Paket\integrationtests\Paket.IntegrationTests\Paket.IntegrationTests.fsproj" (5) on node 6 (Restore target(s)).
     5>C:\github\Paket\integrationtests\Paket.IntegrationTests\Paket.IntegrationTests.fsproj : error MSB4057: The target "Restore" does not exist in the project.
     5>Done Building Project "C:\github\Paket\integrationtests\Paket.IntegrationTests\Paket.IntegrationTests.fsproj" (Restore target(s)) -- FAILED.
     1>Project "C:\github\Paket\Paket.sln" (1) is building "C:\github\Paket\tests\Paket.Bootstrapper.Tests\Paket.Bootstrapper.Tests.csproj" (6) on node 5 (Restore target(s)).
     6>C:\github\Paket\tests\Paket.Bootstrapper.Tests\Paket.Bootstrapper.Tests.csproj : error MSB4057: The target "Restore" does not exist in the project.
     1>Project "C:\github\Paket\Paket.sln" (1) is building "C:\github\Paket\src\Paket.Bootstrapper\Paket.Bootstrapper.csproj" (7) on node 3 (Restore target(s)).
     7>C:\github\Paket\src\Paket.Bootstrapper\Paket.Bootstrapper.csproj : error MSB4057: The target "Restore" does not exist in the project.
     6>Done Building Project "C:\github\Paket\tests\Paket.Bootstrapper.Tests\Paket.Bootstrapper.Tests.csproj" (Restore target(s)) -- FAILED.
     7>Done Building Project "C:\github\Paket\src\Paket.Bootstrapper\Paket.Bootstrapper.csproj" (Restore target(s)) -- FAILED.
     1>Done Building Project "C:\github\Paket\Paket.sln" (Restore target(s)) -- FAILED.

Build FAILED.

       "C:\github\Paket\Paket.sln" (Restore target) (1) ->
       "C:\github\Paket\tests\Paket.Tests\Paket.Tests.fsproj" (Restore target) (2) ->
         C:\github\Paket\tests\Paket.Tests\Paket.Tests.fsproj : error MSB4057: The target "Restore" does not exist in the project.


       "C:\github\Paket\Paket.sln" (Restore target) (1) ->
       "C:\github\Paket\src\Paket.Core\Paket.Core.fsproj" (Restore target) (3) ->
         C:\github\Paket\src\Paket.Core\Paket.Core.fsproj : error MSB4057: The target "Restore" does not exist in the project.


       "C:\github\Paket\Paket.sln" (Restore target) (1) ->
       "C:\github\Paket\src\Paket\Paket.fsproj" (Restore target) (4) ->
         C:\github\Paket\src\Paket\Paket.fsproj : error MSB4057: The target "Restore" does not exist in the project.


       "C:\github\Paket\Paket.sln" (Restore target) (1) ->
       "C:\github\Paket\integrationtests\Paket.IntegrationTests\Paket.IntegrationTests.fsproj" (Restore target) (5) ->
         C:\github\Paket\integrationtests\Paket.IntegrationTests\Paket.IntegrationTests.fsproj : error MSB4057: The target "Restore" does not exist in the project.


       "C:\github\Paket\Paket.sln" (Restore target) (1) ->
       "C:\github\Paket\tests\Paket.Bootstrapper.Tests\Paket.Bootstrapper.Tests.csproj" (Restore target) (6) ->
         C:\github\Paket\tests\Paket.Bootstrapper.Tests\Paket.Bootstrapper.Tests.csproj : error MSB4057: The target "Restore" does not exist in the project.


       "C:\github\Paket\Paket.sln" (Restore target) (1) ->
       "C:\github\Paket\src\Paket.Bootstrapper\Paket.Bootstrapper.csproj" (Restore target) (7) ->
         C:\github\Paket\src\Paket.Bootstrapper\Paket.Bootstrapper.csproj : error MSB4057: The target "Restore" does not exist in the project.

    0 Warning(s)
    6 Error(s)

Time Elapsed 00:00:00.14

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target           Duration
------           --------
Clean            00:00:00.0248614
AssemblyInfo     00:00:00.0347605
Total:           00:00:00.7780143
---------------------------------------------------------------------
---------------------------------------------------------------------
---------------------------------------------------------------------
---------------------------------------------------------------------
```

I have dotnet preview2 installed and in path:

```
λ dotnet --version
2.0.0-preview2-006067
```

Invoking `dotnet restore` results in:

```
λ dotnet restore
C:\github\Paket\tests\Paket.Tests\Paket.Tests.fsproj : error MSB4057: The target "_GenerateRestoreProjectPathWalk" does not exist in the project.
C:\github\Paket\src\Paket\Paket.fsproj : error MSB4057: The target "_GenerateRestoreProjectPathWalk" does not exist in the project.
C:\github\Paket\src\Paket.Core\Paket.Core.fsproj : error MSB4057: The target "_GenerateRestoreProjectPathWalk" does not exist in the project.
C:\github\Paket\integrationtests\Paket.IntegrationTests\Paket.IntegrationTests.fsproj : error MSB4057: The target "_GenerateRestoreProjectPathWalk" does not exist in the project.
  Restoring packages for C:\github\Paket\src\Paket.Bootstrapper\Paket.Bootstrapper.csproj...
  Generating MSBuild file C:\github\Paket\src\Paket.Bootstrapper\obj\Paket.Bootstrapper.csproj.nuget.g.props.
  Generating MSBuild file C:\github\Paket\src\Paket.Bootstrapper\obj\Paket.Bootstrapper.csproj.nuget.g.targets.
  Writing lock file to disk. Path: C:\github\Paket\src\Paket.Bootstrapper\obj\project.assets.json
  Restore completed in 81.76 ms for C:\github\Paket\src\Paket.Bootstrapper\Paket.Bootstrapper.csproj.
  
  NuGet Config files used:
      C:\github\Paket\NuGet.Config
      C:\Users\BRE44821\AppData\Roaming\NuGet\NuGet.Config
  
  Feeds used:
      https://api.nuget.org/v3/index.json
```

Any tips?

**Comment by forki** [comment]
@enricosada ideas?

Am 17.05.2017 8:39 nachm. schrieb "Tomasz Heimowski" <
notifications@github.com>:

**Comment by forki** [comment]
@enricosada any ideas what's missing?

**Comment by enricosada** [comment]
no @forki , this is new. i'll try locally tomorrow

**Comment by forki** [comment]
fixed in master.

**Comment by theimowski** [comment]
I'm still getting the same errors, but now (5.0.0-beta005) instead of `Restore` target it errors on `Rebuild` target

**Comment by forki** [comment]
you used latest master commit?
can you please show complete error?

**Comment by forki** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/57396/26350994/dc42cb64-3fb5-11e7-8724-1b8fa1e560fe.png)

what if you add these lines?

**Comment by theimowski** [comment]
yes, 00b0bd46d 

added those two lines, still the same

`> build`:

```
Paket version 5.0.0-beta005
1 second - ready.
Building project with version: LocalBuild
Shortened DependencyGraph for Target All:
<== All
   <== GenerateDocs
      <== GenerateReferenceDocs
         <== RunTests
            <== Build
               <== Clean
               <== AssemblyInfo
            <== BuildCore
               <== DotnetPackage
                  <== DotnetBuild
                     <== DotnetRestore
                        <== InstallDotNetCore
         <== GenerateHelp
            <== CleanDocs

The running order is:
  - Clean
  - AssemblyInfo
  - Build
  - InstallDotNetCore
  - DotnetRestore
  - DotnetBuild
  - DotnetPackage
  - BuildCore
  - RunTests
  - CleanDocs
  - GenerateHelp
  - GenerateReferenceDocs
  - GenerateDocs
  - All
Running build with 1 worker
Starting Target: Clean 
Deleting contents of c:\github\Paket\src\Paket.Bootstrapper\obj
Deleting contents of c:\github\Paket\tests\Paket.Bootstrapper.Tests\obj
Deleting contents of c:\github\Paket\tests\Paket.Bootstrapper.Tests\bin
Deleting contents of c:\github\Paket\bin
Finished Target: Clean
Starting Target: AssemblyInfo (==> Clean)
Created AssemblyInfo file "src\Paket\AssemblyInfo.fs".
Created AssemblyInfo file "src\Paket.Core\AssemblyInfo.fs".
Created AssemblyInfo file "c:\github\Paket\src\Paket.Bootstrapper\Properties\AssemblyInfo.cs".
Finished Target: AssemblyInfo
Starting Target: Build (==> Clean, AssemblyInfo)
Building project: c:\github\Paket\Paket.sln
  C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe  c:\github\Paket\Paket.sln /t:Rebuild /m      /p:RestorePackages="False" /p:Configuration="Release" /p:SourceLinkCreate="true" /logger:Fake.MsBuildLogger+ErrorLogger,"c:\github\Paket\packages\build\FAKE\tools\FakeLib.dll"
Microsoft (R) Build Engine version 15.1.1012.6693
Copyright (C) Microsoft Corporation. All rights reserved.

Build started 5/23/2017 12:45:13 PM.
     1>Project "c:\github\Paket\Paket.sln" on node 1 (Rebuild target(s)).
     1>ValidateSolutionConfiguration:
         Building solution configuration "Release|Any CPU".
     1>Project "c:\github\Paket\Paket.sln" (1) is building "c:\github\Paket\tests\Paket.Tests\Paket.Tests.fsproj" (2) on node 1 (Rebuild target(s)).
     2>c:\github\Paket\tests\Paket.Tests\Paket.Tests.fsproj : error MSB4057: The target "Rebuild" does not exist in the project.
     2>Done Building Project "c:\github\Paket\tests\Paket.Tests\Paket.Tests.fsproj" (Rebuild target(s)) -- FAILED.
     1>Project "c:\github\Paket\Paket.sln" (1) is building "c:\github\Paket\src\Paket\Paket.fsproj" (3) on node 2 (Rebuild target(s)).
     3>c:\github\Paket\src\Paket\Paket.fsproj : error MSB4057: The target "Rebuild" does not exist in the project.
     3>Done Building Project "c:\github\Paket\src\Paket\Paket.fsproj" (Rebuild target(s)) -- FAILED.
     1>Project "c:\github\Paket\Paket.sln" (1) is building "c:\github\Paket\src\Paket.Core\Paket.Core.fsproj" (4) on node 4 (Rebuild target(s)).
     4>c:\github\Paket\src\Paket.Core\Paket.Core.fsproj : error MSB4057: The target "Rebuild" does not exist in the project.
     4>Done Building Project "c:\github\Paket\src\Paket.Core\Paket.Core.fsproj" (Rebuild target(s)) -- FAILED.
     1>Project "c:\github\Paket\Paket.sln" (1) is building "c:\github\Paket\integrationtests\Paket.IntegrationTests\Paket.IntegrationTests.fsproj" (5) on node 6 (Rebuild target(s)).
     5>c:\github\Paket\integrationtests\Paket.IntegrationTests\Paket.IntegrationTests.fsproj : error MSB4057: The target "Rebuild" does not exist in the project.
     5>Done Building Project "c:\github\Paket\integrationtests\Paket.IntegrationTests\Paket.IntegrationTests.fsproj" (Rebuild target(s)) -- FAILED.
     1>Project "c:\github\Paket\Paket.sln" (1) is building "c:\github\Paket\src\Paket.Bootstrapper\Paket.Bootstrapper.csproj" (6) on node 3 (Rebuild target(s)).
     6>CoreClean:
         Creating directory "obj\Release\".
     1>Project "c:\github\Paket\Paket.sln" (1) is building "c:\github\Paket\tests\Paket.Bootstrapper.Tests\Paket.Bootstrapper.Tests.csproj" (7) on node 5 (Rebuild target(s)).
     7>CoreClean:
         Creating directory "obj\Release\".
     6>GenerateTargetFrameworkMonikerAttribute:
       Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
       CoreCompile:
         C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Roslyn\csc.exe /noconfig /unsafe- /nowarn:1701,1702 /nostdlib+ /platform:anycpu32bitpreferred /errorreport:prompt /warn:4 /define:TRACE /highentropyva+ /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Configuration.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Data.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.IO.Compression.FileSystem.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xml.dll" /debug:pdbonly /filealign:512 /optimize+ /out:obj\Release\paket.bootstrapper.exe /subsystemversion:6.00 /target:exe /utf8output ArgumentParser.cs BootstrapperHelper.cs BootstrapperOptions.cs DownloadStrategies\IDownloadStrategy.cs DownloadStrategies\IHaveEffectiveStrategy.cs PaketDependencies.cs PaketRunner.cs Verbosity.cs WindowsProcessArguments.cs DownloadStrategies\CacheDownloadStrategy.cs HelperProxies\IWebRequestProxy.cs HelperProxies\WebRequestProxy.cs DownloadArguments.cs EnvProxy.cs HelperProxies\FileSystemProxy.cs DownloadStrategies\GitHubDownloadStrategy.cs DownloadStrategies\DownloadStrategy.cs HelperProxies\IFileSystemProxy.cs DownloadStrategies\NugetDownloadStrategy.cs ConsoleImpl.cs Program.cs Properties\AssemblyInfo.cs SemVer.cs DownloadStrategies\TemporarilyIgnoreUpdatesDownloadStrategy.cs HelperProxies\DateTimeProxy.cs "C:\Users\BRE44821\AppData\Local\Temp\.NETFramework,Version=v4.5.AssemblyAttributes.cs"
         Using shared compilation with compiler from directory: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Roslyn
       CopyFilesToOutputDirectory:
         Copying file from "obj\Release\paket.bootstrapper.exe" to "..\..\bin\paket.bootstrapper.exe".
         Paket.Bootstrapper -> c:\github\Paket\bin\paket.bootstrapper.exe
         Copying file from "obj\Release\paket.bootstrapper.pdb" to "..\..\bin\paket.bootstrapper.pdb".
     6>Done Building Project "c:\github\Paket\src\Paket.Bootstrapper\Paket.Bootstrapper.csproj" (Rebuild target(s)).
     7>PrepareForBuild:
         Creating directory "bin\Release\".
       GenerateTargetFrameworkMonikerAttribute:
       Skipping target "GenerateTargetFrameworkMonikerAttribute" because all output files are up-to-date with respect to the input files.
       CoreCompile:
         C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Roslyn\csc.exe /noconfig /nowarn:1701,1702 /nostdlib+ /errorreport:prompt /warn:4 /define:TRACE /highentropyva+ /reference:c:\github\Paket\packages\test\Castle.Core\lib\net45\Castle.Core.dll /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Microsoft.CSharp.dll" /reference:c:\github\Paket\packages\test\Moq\lib\net45\Moq.dll /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\mscorlib.dll" /reference:c:\github\Paket\packages\test\NUnit\lib\net45\nunit.framework.dll /reference:c:\github\Paket\bin\paket.bootstrapper.exe /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.ComponentModel.Composition.dll" /reference:c:\github\Paket\packages\test\System.ComponentModel.Primitives\lib\net45\System.ComponentModel.Primitives.dll /reference:c:\github\Paket\packages\test\System.ComponentModel.TypeConverter\lib\net45\System.ComponentModel.TypeConverter.dll /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Core.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Net.Http.dll" /reference:c:\github\Paket\packages\test\System.Threading.Tasks.Extensions\lib\netstandard1.0\System.Threading.Tasks.Extensions.dll /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Collections.Concurrent.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Collections.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.ComponentModel.Annotations.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.ComponentModel.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.ComponentModel.EventBasedAsync.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Diagnostics.Contracts.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Diagnostics.Debug.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Diagnostics.Tools.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Diagnostics.Tracing.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Dynamic.Runtime.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Globalization.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.IO.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Linq.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Linq.Expressions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Linq.Parallel.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Linq.Queryable.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Net.NetworkInformation.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Net.Primitives.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Net.Requests.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.ObjectModel.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Reflection.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Reflection.Emit.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Reflection.Emit.ILGeneration.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Reflection.Emit.Lightweight.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Reflection.Extensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Reflection.Primitives.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Resources.ResourceManager.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Runtime.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Runtime.Extensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Runtime.InteropServices.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Runtime.InteropServices.WindowsRuntime.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Runtime.Numerics.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Runtime.Serialization.Json.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Runtime.Serialization.Primitives.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Runtime.Serialization.Xml.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Security.Principal.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.ServiceModel.Duplex.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.ServiceModel.Http.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.ServiceModel.NetTcp.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.ServiceModel.Primitives.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.ServiceModel.Security.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Text.Encoding.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Text.Encoding.Extensions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Text.RegularExpressions.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Threading.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Threading.Tasks.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Threading.Tasks.Parallel.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Xml.ReaderWriter.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Xml.XDocument.dll" /reference:"C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\Facades\System.Xml.XmlSerializer.dll" /debug:pdbonly /filealign:512 /optimize+ /out:obj\Release\Paket.Bootstrapper.Tests.dll /subsystemversion:6.00 /target:library /warnaserror+ /utf8output ArgumentParserTests.cs DownloadStrategies\CacheDownloadStrategyTest.cs DownloadStrategies\NugetApiHelperTests.cs DownloadStrategies\NugetDownloadStrategyTests.cs EnvWebProxyShould.cs ProgramTests.cs DownloadStrategies\GitHubDownloadStrategyTest.cs SemVerTests.cs StartPaketBootstrappingTests.cs DownloadStrategies\TemporarilyIgnoreUpdatesDownloadStrategyTest.cs WindowsProcessArgumentsParseTests.cs WindowsProcessArgumentsToStringTests.cs "C:\Users\BRE44821\AppData\Local\Temp\.NETFramework,Version=v4.5.AssemblyAttributes.cs"
         Using shared compilation with compiler from directory: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\Roslyn
       _CopyFilesMarkedCopyLocal:
         Copying file from "c:\github\Paket\packages\test\Castle.Core\lib\net45\Castle.Core.dll" to "bin\Release\Castle.Core.dll".
         Copying file from "c:\github\Paket\packages\test\Moq\lib\net45\Moq.dll" to "bin\Release\Moq.dll".
         Copying file from "c:\github\Paket\packages\test\NUnit\lib\net45\nunit.framework.dll" to "bin\Release\nunit.framework.dll".
         Copying file from "c:\github\Paket\bin\paket.bootstrapper.exe" to "bin\Release\paket.bootstrapper.exe".
         Copying file from "c:\github\Paket\packages\test\System.ComponentModel.Primitives\lib\net45\System.ComponentModel.Primitives.dll" to "bin\Release\System.ComponentModel.Primitives.dll".
         Copying file from "c:\github\Paket\packages\test\System.ComponentModel.TypeConverter\lib\net45\System.ComponentModel.TypeConverter.dll" to "bin\Release\System.ComponentModel.TypeConverter.dll".
         Copying file from "c:\github\Paket\packages\test\System.Threading.Tasks.Extensions\lib\netstandard1.0\System.Threading.Tasks.Extensions.dll" to "bin\Release\System.Threading.Tasks.Extensions.dll".
         Copying file from "c:\github\Paket\bin\paket.bootstrapper.pdb" to "bin\Release\paket.bootstrapper.pdb".
         Copying file from "c:\github\Paket\packages\test\Castle.Core\lib\net45\Castle.Core.xml" to "bin\Release\Castle.Core.xml".
         Copying file from "c:\github\Paket\packages\test\Moq\lib\net45\Moq.xml" to "bin\Release\Moq.xml".
         Copying file from "c:\github\Paket\packages\test\NUnit\lib\net45\nunit.framework.xml" to "bin\Release\nunit.framework.xml".
         Copying file from "c:\github\Paket\packages\test\System.Threading.Tasks.Extensions\lib\netstandard1.0\System.Threading.Tasks.Extensions.xml" to "bin\Release\System.Threading.Tasks.Extensions.xml".
       _CopyAppConfigFile:
         Copying file from "app.config" to "bin\Release\Paket.Bootstrapper.Tests.dll.config".
       CopyFilesToOutputDirectory:
         Copying file from "obj\Release\Paket.Bootstrapper.Tests.dll" to "bin\Release\Paket.Bootstrapper.Tests.dll".
         Paket.Bootstrapper.Tests -> c:\github\Paket\tests\Paket.Bootstrapper.Tests\bin\Release\Paket.Bootstrapper.Tests.dll
         Copying file from "obj\Release\Paket.Bootstrapper.Tests.pdb" to "bin\Release\Paket.Bootstrapper.Tests.pdb".
     7>Done Building Project "c:\github\Paket\tests\Paket.Bootstrapper.Tests\Paket.Bootstrapper.Tests.csproj" (Rebuild target(s)).
     1>Done Building Project "c:\github\Paket\Paket.sln" (Rebuild target(s)) -- FAILED.

Build FAILED.

       "c:\github\Paket\Paket.sln" (Rebuild target) (1) ->
       "c:\github\Paket\tests\Paket.Tests\Paket.Tests.fsproj" (Rebuild target) (2) ->
         c:\github\Paket\tests\Paket.Tests\Paket.Tests.fsproj : error MSB4057: The target "Rebuild" does not exist in the project.


       "c:\github\Paket\Paket.sln" (Rebuild target) (1) ->
       "c:\github\Paket\src\Paket\Paket.fsproj" (Rebuild target) (3) ->
         c:\github\Paket\src\Paket\Paket.fsproj : error MSB4057: The target "Rebuild" does not exist in the project.


       "c:\github\Paket\Paket.sln" (Rebuild target) (1) ->
       "c:\github\Paket\src\Paket.Core\Paket.Core.fsproj" (Rebuild target) (4) ->
         c:\github\Paket\src\Paket.Core\Paket.Core.fsproj : error MSB4057: The target "Rebuild" does not exist in the project.


       "c:\github\Paket\Paket.sln" (Rebuild target) (1) ->
       "c:\github\Paket\integrationtests\Paket.IntegrationTests\Paket.IntegrationTests.fsproj" (Rebuild target) (5) ->
         c:\github\Paket\integrationtests\Paket.IntegrationTests\Paket.IntegrationTests.fsproj : error MSB4057: The target "Rebuild" does not exist in the project.

    0 Warning(s)
    4 Error(s)

Time Elapsed 00:00:01.86

---------------------------------------------------------------------
Build Time Report
---------------------------------------------------------------------
Target         Duration
------         --------
Clean          00:00:00.0335430
AssemblyInfo   00:00:00.0322633
Total:         00:00:02.5598670
---------------------------------------------------------------------
---------------------------------------------------------------------
---------------------------------------------------------------------
---------------------------------------------------------------------
```

`> dotnet restore`:

```
c:\github\Paket\tests\Paket.Tests\Paket.Tests.fsproj : error MSB4057: The target "_GenerateRestoreProjectPathWalk" does not exist in the project.
c:\github\Paket\src\Paket\Paket.fsproj : error MSB4057: The target "_GenerateRestoreProjectPathWalk" does not exist in the project.
c:\github\Paket\src\Paket.Core\Paket.Core.fsproj : error MSB4057: The target "_GenerateRestoreProjectPathWalk" does not exist in the project.
c:\github\Paket\integrationtests\Paket.IntegrationTests\Paket.IntegrationTests.fsproj : error MSB4057: The target "_GenerateRestoreProjectPathWalk" does not exist in the project.
  Restoring packages for c:\github\Paket\src\Paket.Bootstrapper\Paket.Bootstrapper.csproj...
  Generating MSBuild file c:\github\Paket\src\Paket.Bootstrapper\obj\Paket.Bootstrapper.csproj.nuget.g.props.
  Generating MSBuild file c:\github\Paket\src\Paket.Bootstrapper\obj\Paket.Bootstrapper.csproj.nuget.g.targets.
  Writing lock file to disk. Path: c:\github\Paket\src\Paket.Bootstrapper\obj\project.assets.json
  Restore completed in 92.27 ms for c:\github\Paket\src\Paket.Bootstrapper\Paket.Bootstrapper.csproj.
  
  NuGet Config files used:
      c:\github\Paket\NuGet.Config
      C:\Users\BRE44821\AppData\Roaming\NuGet\NuGet.Config
  
  Feeds used:
      https://api.nuget.org/v3/index.json

```

**Comment by forki** [comment]
it's using Microsoft (R) Build Engine version 15.1.1012.6693 <- that's not correct. it should use 14

**Comment by theimowski** [comment]
can I make it do so, without uninstalling VS 2017?

**Comment by forki** [comment]
yes I was hoping the two lines are doing this

**Comment by matthid** [comment]
I can actually build fine with 15
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe`
exactly the same version:
`Microsoft (R) Build Engine version 15.1.1012.6693`

@theimowski Can you try with the cli tools 1.0.4 (ie uninstall 2.0). I'm not sure if msbuild is running on netcore now but maybe it is?

**Comment by theimowski** [comment]
@matthid I get exactly the same error when downgrading cli to 1.0.4.
I have both cli 1.0.4 (official installer) and 2.0 (extracted binaries) - just changing my path variable.
I can however build from within VS both 2015 and 2017

**Comment by matthid** [comment]
@theimowski  The only obvious difference is that for you FAKE is picking up a different msbuild path:

`C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe`

Can you try setting the `MSBuild` environment variable. To msbuild 14 (for testing purposes), see https://github.com/fsharp/FAKE/blob/master/src/app/FakeLib/MSBuildHelper.fs

We apparently even support the `VisualStudioVersion` environment variable, so maybe running from a Developer Command line prompt could work as well?

**Comment by theimowski** [comment]
Yep - both setting `MSBuild` variable and running from Developer Command Line worked 👍  
What can be done to make it work from standard cmd without setting env vars?

**Comment by matthid** [comment]
What developer command line vs2017 or vs2015 or both?

**Comment by theimowski** [comment]
both

**Comment by matthid** [comment]
Can you post the output for the vs2017 one?

**Comment by matthid** [comment]
Related: https://github.com/cake-build/cake/issues/1369

**Comment by matthid** [comment]
> MSBuild should be present in every install of VS2017 (that I know of). But the tasks, targets, and other extensions required to build a specific project may not be available in every instance. To be fully robust, you probably want to query for a specific workload/component corresponding to your project type (for example, you might know that you need Microsoft.VisualStudio.WCF).

wtf

**Comment by matthid** [comment]
Basically means all the failures we are seeing throughout are not msbuild 15 bugs but features...

**Comment by matthid** [comment]
https://github.com/fsharp/FAKE/commit/e28e53ddf953832e8f97ba1d5d01ce271788c534 might fix it

**Comment by theimowski** [comment]
Attaching output of `build` command from Developer Command Line 2017 - it's over 1K lines 

[out.txt](https://github.com/fsprojects/Paket/files/1031518/out.txt)

**Comment by matthid** [comment]
Ok thanks, this will make me apply a different fix, apparently we reverted the path list and always preferred the `BuildTools` folder if it was available...

**Comment by matthid** [comment]
@theimowski can you try again with latest master (where we updated FAKE)?

**Comment by theimowski** [comment]
Thanks @matthid  works like a charm now
