### ISSUE TITLE
Multi-target dotnet restore/build problem with Paket

### ISSUE THREAD

**Issue by jackfoxy** [fsprojects/Paket#2953]
### Description

Muti-target dotnet restore problem with Paket

\<TargetFramework>net45\</TargetFramework>

\<TargetFramework>net47\</TargetFramework>

\<TargetFramework>netstandard2.0\</TargetFramework>

all build correctly,

but the multi-target builds

\<TargetFrameworks>net45;net47\</TargetFrameworks>

\<TargetFrameworks>net47;netstandard2.0\</TargetFrameworks>

fail to resolve the package reference Argu.

The multi-target builds have been verified to work when the project uses nuget package references instead of Paket. See https://github.com/jackfoxy/MultiTargetNuget

### Repro steps

Test repo https://github.com/jackfoxy/MultiTargetPaket

every time the build targets change

- paket update -f 
- dotnet restore

### Expected behavior

The package reference Argu should resolve and the build succeed.

The build does succeed when performed against a single target framework.

### Actual behavior

Fail to resolve the package reference Argu on mult-framework project.

### Known workarounds

Use Nuget package references. See https://github.com/jackfoxy/MultiTargetNuget

**Comment by forki** [comment]
Ok. just took a look. The problem is with framework:auto-detect. Remove that from the deps file, run update and it works.

**Comment by eiriktsarpalis** [comment]
`framework:auto-detect` was certainly one of the things causing me problems

**Comment by forki** [comment]
Yeah. That one is not working yet with multi target. Maybe I can fix it
tomorrow

Am 01.01.2018 10:41 schrieb "Eirik Tsarpalis" <notifications@github.com>:

**Comment by eiriktsarpalis** [comment]
I can [reproduce](https://github.com/eiriktsarpalis/Repro/tree/0fd1a5ecd3caeeea630c840438de7d32ad586767) without `auto-detect` enabled. TL;DR build fails for net45 because a nuget packages for that target aren't being restored.
![image](https://user-images.githubusercontent.com/2813363/34468001-c9ea3060-eef6-11e7-9f3c-ad9eed34185a.png)

**Comment by forki** [comment]
Ok will look into that as well. Thanks

Am 01.01.2018 14:22 schrieb "Eirik Tsarpalis" <notifications@github.com>:

**Comment by jackfoxy** [comment]
@eiriktsarpalis  I would sometimes see System.RunTime.DLL missing for net45 and net47. It was not consistent, when I stopped using dependency groups the problem went away.

**Comment by jackfoxy** [comment]
@forki  confirmed the workaround works for me.
What advantage does auto-detect have in the world of dotnet project files? 
Seems like Paket may have downloaded more packages without it.

**Comment by forki** [comment]
Tbh Auto-detect was never really bug free. Currently it does not work at all for multi targeting. I have WIP, so that may change tomorrow.

Regarding advantages: it has no advantages if you maintain the list of framework restrictions manually in the dependencies file apart from that the tool will figure it out. 

It was introduced to make it easier for users to get that information maintained, but it comes with a bit runtime cost since paket needs to scan your folders for projects. 

Regarding number of packages. If you just remove the Auto-detect then it will download for all frameworks. That may be more than before. That's expected.

**Comment by jackfoxy** [comment]
Not having to maintain the list of restrictions manually is an advantage!

**Comment by jackfoxy** [comment]
One other thing I noticed (IIRC) <TargetFrameworks> will work for a single target in Nuget, but not Paket

**Comment by forki** [comment]
I fixed multi targeting. @jackfoxy can you please retry?

**Comment by eiriktsarpalis** [comment]
Using paket 5.128.3 didn't fix the issue for me in the reproducing repo.

**Comment by forki** [comment]
@eiriktsarpalis I didn't look into your issue yet. This was only the thing @jackfoxy reported

**Comment by forki** [comment]
@eiriktsarpalis 

dotnet build gives me:

![image](https://user-images.githubusercontent.com/57396/34489093-0fca97d4-efdb-11e7-8f30-e57dbcf7f8fe.png)

that looks unrelated?

**Comment by forki** [comment]
ok found the bug. workaround: remove the empty space in the targets definition:

![image](https://user-images.githubusercontent.com/57396/34489171-7fa63ce8-efdb-11e7-8d38-72e5526e8a79.png)

working on a fix.

**Comment by eiriktsarpalis** [comment]
Confirming that removing whitespace fixed the issue.

**Comment by jackfoxy** [comment]
@forki  I put framework: auto-detect back in dependencies.
Ran paket.boostrapper which downloaded Version 5.128.3.
paket update -f
dotnet restore

...and multitarget ````<TargetFrameworks>net47;netstandard2.0</TargetFrameworks>```` built!

**Comment by jackfoxy** [comment]
Also ````<TargetFrameworks>netstandard2.0</TargetFrameworks>```` (note frameworks plural) now builds, which I think was a problem before.

**Comment by jackfoxy** [comment]
@forki  I think you can close this.

**Comment by forki** [comment]
waiting for confirmation that .4 fixes that issue with additional space.
Release is under way

**Comment by forki** [comment]
@eiriktsarpalis it's now fixed for me. with .4 your repro builds fine for me

**Comment by eiriktsarpalis** [comment]
Thank you 👍
