### ISSUE TITLE
binding redirect should not use clitool dependencies

### ISSUE THREAD

**Issue by ctaggart** [fsprojects/Paket#2955]
See https://github.com/fsprojects/Argu/pull/99. tests/Argu.Core.Tests/App.config is being populated with dependencies from `dotnet-sourcelink`. That should not happen.

Paket version 5.128.0

**Comment by forki** [comment]
@ctaggart can you please retry?

**Comment by ctaggart** [comment]
@forki, I keep getting:
```
C:\Users\camer\fs\Argu [sourcelink.test ≡ +0 ~1 -0 !]> .\.paket\paket.exe update --clean-redirects
...
Paket failed with
-> Package directory for package Microsoft.CSharp was not found.
```

I deleted the folder from a couple of caches, but still same issue.

**Comment by forki** [comment]
ok I can repro. Looking into it

**Comment by forki** [comment]
fixed.

**Comment by ctaggart** [comment]
I no longer get the error about `Microsoft.CSharp was not found`. However, this issue about app.config containing redirect for the clitool is not yet fixed with paket 5.129.0. 

Microsoft.Extensions.CommandLineUtils should not be in the app.config.
![image](https://user-images.githubusercontent.com/80104/34529716-eb715d32-f07a-11e7-8078-a7f0cc7c9582.png)

**Comment by forki** [comment]
Mhm something still fucky. Sorry. Will investigate tomorrow

**Comment by forki** [comment]
oh it's not directly a clitool. It's just a dependency of a clitool that is not used somewhere else.
That's tricky ;-)
